name: 良仔的博客
author: liangren.com
#baseurl: /liangren.com
keywords: java,github,git,jekyll,gollum,jquery,flash,良先生,良仔
description: 一个小白码农的博客
github: https://github.com/liangrengongzuoshi
email: crawler_vip@163.com


encoding: utf-8
#highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
