name: 软件收藏https://dagaoya.github.com
author: dagaoya
#baseurl: /liangren.com
keywords: github,jekyll,软件收藏,工具
description: 一个软件收藏的界面
github: https://github.com/dagaoya
email: NoEmail


encoding: utf-8
#highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
